name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
      - name: Test application with eslint
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deployment...
